### ISSUE TITLE
Confusion when reading code

### ISSUE THREAD

**Issue by rodman10** [Kong/lua-resty-timer-ng#16]
When I read the source code, I was confused by the following code
https://github.com/Kong/lua-resty-timer-ng/blob/main/lib/resty/timerng/job.lua#L254C17-L254C27
whether the `immediate` in the above code should be replaced by `_immediate` ? Is it a typo? Thanks for reply :) !

**Comment by ADD-SP** [comment]
Yes, it is a typo. Luckily, it doesn't cause any bugs, just useless calculations. Thank you @rodman10 .

**PR welcome!**
